# Combining all cleaned data

## Danny Files
- food security
- SDG indicators
- population

## Sophie Files
- finance data

## Ella Files


## Loading in datasets

```{r}
library(tidyverse)
library(dplyr)

finance_data <- read.csv("../clean_data/finance_data_01to22.csv")
finance_data_short <- read.csv("../clean_data/finance_data_17to22.csv")

population_data <- read.csv("../clean_data/population_clean.csv")
population_data_short <- read.csv("../clean_data/population_clean_short.csv")

food_security_data <- read.csv("../clean_data/Food_Security_Clean.csv")
food_security_data_short <- read.csv("../clean_data/Food_Security_Clean_short.csv")

sdg_data <- read.csv("../clean_data/SDG_Indicators_clean.csv")
sdg_data_short <- read.csv("../clean_data/SDG_Indicators_clean_short.csv")

## Ella files here
```


## Combining Datasets on Year and Country
```{r}
all_data <- finance_data %>%
  full_join(population_data,  by = c("country", "year")) %>%
  full_join(food_security_data,  by = c("country", "year")) %>%
  full_join(sdg_data,  by = c("country", "year"))

all_data_short <- finance_data_short %>%
  full_join(population_data_short,  by = c("country", "year")) %>%
  full_join(food_security_data_short,  by = c("country", "year")) %>%
  full_join(sdg_data_short,  by = c("country", "year"))


file_path <- "../clean_data/combined_data.csv"
write.csv(all_data, file = file_path, row.names = FALSE)

file_path_short <- "../clean_data/combined_data_short.csv"
write.csv(all_data_short, file = file_path_short, row.names = FALSE)
```
